# Generated by Django 5.1.4 on 2025-01-22 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='transport.busstop'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='transport.busstop'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='assigned_students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='assigned_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.assignment'),
        ),
        migrations.AddField(
            model_name='trip',
            name='onboard_students',
            field=models.ManyToManyField(blank=True, related_name='onboard_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle'),
        ),
    ]
